export const Sectors = [
    'AGROALIMENTAIRE' ,
    'HABITAT ET MATÉRIAUX DE CONSTRUCTION',
    'INDUSTRIES CRÉATIVES, SECTEURS CULTURELS, TECHNOLOGIE ET SERVICES',
    'INDUSTRIEL',
    'CONSOMMATION'
]